version: 1.0

# Camera Settings
camera_width: 2592
camera_height: 1944
camera_brightness_min: -64
camera_brightness_max: 64
camera_brightness_standard: 0
camera_contrast_min: -100
camera_contrast_max: 100
camera_contrast_standard: 0
camera_saturation_min: 0
camera_saturation_max: 255
camera_saturation_standard: 128
camera_hue_min: -180
camera_hue_max: 180
camera_hue_standard: 0

# Stream Resolution
stream_width: 1920
stream_height: 1440

# Yolact Parameters
yolact_config: yolact_resnet101_blood_config
yolact_weights: D:\Bachelorarbeit\MicroImagePredictor\weights\yolact_resnet101_blood_6399_96000.pth

# Yolo Parameters
yolo_weights: D:\Leischmanien\MicroPredictor-main\MicroPredictor\weights\leishmania_finetuning.pt
